import * as fs from "node:fs";
import * as path from "node:path";
import { PACKAGE_NAME, VERSION } from "../shared/manifest.js";
import { rewritePins, WORKFLOW_DIR } from "../shared/pins.js";
import { callersIn, readInstalledCallers, repoSlug } from "./callers.js";

/**
 * The install path: scaffold into an adopter's repository what nothing upstream
 * covers, which is the GitHub Actions half of the loop.
 *
 * Since the reference callers became real files under test (#98),
 * `examples/callers/` is the source and this **copies** rather than generates.
 * That is the smaller job and the better one: a generator is a second
 * description of a caller, and the first release after it drifts is one where an
 * adopter installs something the suite has never seen.
 *
 * The one thing in a caller that is per-repo is the **pin**, which should be
 * this package's own version at the time `init` runs, and it is written through
 * the same rewrite the release performs (`shared/pins.ts`).
 *
 * And it **updates on a re-run** rather than refusing. The commonest reason to
 * run this twice is a new release; a scaffolder that says "remove it first" is
 * one an adopter works around by hand, which is how the pin went four releases
 * stale in the repository this loop was piloted on.
 *
 * So a re-run is **not** a second copy. A caller is what an adopter owns
 * (CONTEXT.md) — their trigger, their permissions, the `with:` inputs
 * `docs/ADOPTING.md` §4 ships commented out for them to enable, a job id they
 * renamed, a second job in the same file — and a re-run that rewrote the file
 * from the reference would revert every one of those and report it as
 * `updated`. A pnpm repository that had set `setup: pnpm i --frozen-lockfile`
 * would then die at `npm ci` with nothing saying why: the failure class this
 * whole command exists to remove, recreated by the command itself.
 *
 * Therefore:
 *
 * - a caller **already installed** has its pin moved *in its own text* and
 *   nothing else touched;
 * - a caller **not installed** is copied from the reference, pinned — but only
 *   when this is a first run. Once any caller is installed, the subset an
 *   adopter took is a decision, and a re-run reports what is absent rather than
 *   writing a `pull_request_target` workflow nobody asked for back into their
 *   tree.
 *
 * What drifts as a result — a `permissions:` line a later release added — is
 * exactly what `doctor` names, with the fix, on the same footing as everything
 * else it will not silently change for you.
 */

/**
 * The reference callers, resolved the way a runner resolves its prompt —
 * relative to this module, so the same path works in a checkout and in the
 * tarball `scripts/copy-assets.ts` builds.
 */
const REFERENCE_DIR = path.join(import.meta.dirname, "..", "examples", "callers");

/** The prompt for the judgement work, and the marker that says we wrote it. */
const SETUP_TEMPLATE = path.join(import.meta.dirname, "SETUP.md");
const SETUP_FILE = "SETUP.md";

/**
 * What the template's first line says once substituted. Specific enough that an
 * adopter's own `SETUP.md` cannot match it by accident, and visible enough that
 * deleting the line is how you opt out of having it rewritten.
 */
const setupMarker = (): string => `generated by ${PACKAGE_NAME} init`;

/**
 * The reference filename an adopter gets when nothing is installed yet. The
 * prefix exists so a caller does not collide by filename with the reusable half
 * it calls; `readInstalledCallers` recognises a caller by what it calls, so a
 * rename survives a re-run.
 */
const CALLER_PREFIX = "agent-";

/**
 * A label exactly as it has to be created: the name a workflow filters on, and
 * the colour and description `docs/ADOPTING.md` §3 gives it.
 *
 * Both tables below are a **second copy** of that §3 block — this one feeds
 * `SETUP.md`'s create commands and `doctor`'s missing-label errors, and the doc
 * is what a human reads. Held in step by `tests/agent-cli.test.ts`, which parses
 * §3 and compares, in the spirit of `PIN` in `tests/workflows.test.ts`: a rename
 * or a recolour in either place fails the build by name rather than leaving
 * `init` scaffolding one string and a workflow filtering on another.
 */
export interface LabelSpec {
  readonly name: string;
  readonly color: string;
  readonly description: string;
}

/**
 * The state labels every installation needs, whichever callers were taken.
 * The trigger labels are derived from the callers instead — see `labelsFor`.
 */
export const STATE_LABELS: readonly LabelSpec[] = [
  { name: "agent:in-progress", color: "FBCA04", description: "An agent run is currently active" },
  { name: "agent:blocked", color: "B60205", description: "A run failed or was refused; needs human attention" },
];

export const TRIGGER_LABELS: readonly LabelSpec[] = [
  { name: "agent:implement", color: "0E8A16", description: "Ready for the implement workflow to run" },
  { name: "agent:review", color: "1D76DB", description: "PR is ready for the automated review workflow" },
  { name: "agent:fix", color: "1D76DB", description: "Address review feedback on this PR" },
  { name: "agent:update-branch", color: "5319E7", description: "Refresh this PR branch from its base branch" },
];

/**
 * Which label triggers a given workflow. `implement-prd` shares `agent:implement`
 * with `implement` — the two partition every label event by issue shape — so it
 * contributes no label of its own.
 */
export const triggerLabel = (workflow: string): string =>
  `agent:${workflow === "implement-prd" ? "implement" : workflow}`;

/** The labels an installation of exactly these workflows needs, in a stable order. */
export const labelSpecsFor = (workflows: readonly string[]): readonly LabelSpec[] => [
  ...TRIGGER_LABELS.filter((label) =>
    workflows.some((workflow) => triggerLabel(workflow) === label.name),
  ),
  ...STATE_LABELS,
];

/** The same, by name — what `doctor` compares against the repository's labels. */
export const labelsFor = (workflows: readonly string[]): readonly string[] =>
  labelSpecsFor(workflows).map((label) => label.name);

export interface InitChange {
  /** Repo-relative, forward-slashed. */
  readonly file: string;
  /**
   * `kept` is the one that is a **refusal**: a file this will not write over,
   * or a caller an adopter does not have and this will not add for them. It
   * always carries the note saying which.
   */
  readonly action: "created" | "updated" | "unchanged" | "kept";
  /** Why — mandatory on `kept`, since a refusal nobody can read is a silence. */
  readonly note?: string;
}

export interface InitOptions {
  /** The adopting repository's root. */
  readonly dir: string;
}

const referenceFiles = (): readonly string[] =>
  fs
    .readdirSync(REFERENCE_DIR)
    .filter((entry) => entry.endsWith(".yml"))
    .sort();

/**
 * Read back what is about to be written and check the one coupling that has no
 * runtime symptom: `self-check` must name the job it sits in.
 *
 * The pin is a text edit against a file this does not own, and this reads the
 * result the way GitHub would rather than trusting that a regex was applied. A
 * `self-check` naming some other job is a review that waits for itself for 15 of
 * its 20 minutes and then reviews on degraded evidence — precisely the class of
 * defect that must not reach an adopter's disk, and the one thing here that no
 * test in *their* repository could catch.
 */
const assertCoupled = (text: string, file: string): void => {
  const written = callersIn(text, PACKAGE_NAME, file)[0];

  if (written === undefined) {
    throw new Error(`Refusing to write ${file}: it declares no job calling ${PACKAGE_NAME}.`);
  }
  const named = written.selfCheck?.split("/")[0]?.trim();
  if (written.selfCheck !== undefined && named !== written.jobId) {
    throw new Error(
      `Refusing to write ${file}: \`self-check\` would be ${JSON.stringify(written.selfCheck)} on a ` +
        `job whose id is \`${written.jobId}\`. The check run is named ` +
        `\`<caller job id> / <called job id>\`, so the wait would not recognise its own and would ` +
        `wait for itself.`,
    );
  }
};

/** What a write did, without writing the same bytes twice. */
const put = (full: string, text: string): "created" | "updated" | "unchanged" => {
  if (!fs.existsSync(full)) {
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, text);
    return "created";
  }
  if (fs.readFileSync(full, "utf8") === text) return "unchanged";
  fs.writeFileSync(full, text);
  return "updated";
};

const renderSetup = (workflows: readonly string[], callers: readonly string[]): string => {
  const labels = labelSpecsFor(workflows).map(
    ({ name, color, description }) =>
      `gh label create "${name}" --color ${color} --description "${description}"`,
  );

  return fs
    .readFileSync(SETUP_TEMPLATE, "utf8")
    .replaceAll("{{PACKAGE}}", PACKAGE_NAME)
    .replaceAll("{{VERSION}}", VERSION)
    .replaceAll("{{SLUG}}", repoSlug(PACKAGE_NAME))
    .replaceAll("{{CALLERS}}", callers.join("\n"))
    .replaceAll("{{LABELS}}", labels.join("\n"));
};

const pinnedReference = (entry: string, file: string): string => {
  const { text, found } = rewritePins(fs.readFileSync(path.join(REFERENCE_DIR, entry), "utf8"), {
    packageName: PACKAGE_NAME,
    version: VERSION,
  });
  if (!found.includes("ref")) {
    throw new Error(
      `${entry} carries no \`uses:\` pin this version knows how to rewrite. Installing it would ` +
        `point an adopter at whichever release the reference happened to be written against.`,
    );
  }
  assertCoupled(text, file);
  return text;
};

/**
 * Move an installed caller's pin to this version, **in the adopter's own file**.
 *
 * Every other line of it is theirs — see the header. `rewritePins` matches a
 * `@v<major.minor.patch>` ref and nothing else, so a caller deliberately pinned
 * to a SHA, or wrongly pinned to a branch, is reported rather than converted:
 * the first is a choice this has no business overriding and the second is a
 * finding `doctor` already raises by name.
 */
const repin = (dir: string, file: string): InitChange => {
  const full = path.join(dir, ...file.split("/"));
  const { text, found } = rewritePins(fs.readFileSync(full, "utf8"), {
    packageName: PACKAGE_NAME,
    version: VERSION,
  });
  if (!found.includes("ref")) {
    return {
      file,
      action: "kept",
      note: `its \`uses:\` ref is not a \`@v<version>\` tag, so it is left exactly as pinned`,
    };
  }
  return { file, action: put(full, text) };
};

/**
 * Install the reference caller for `entry`, unless something already occupies
 * the filename. A file there that is not one of ours is an adopter's own
 * workflow that happens to share the name, and `put` would overwrite it and
 * report `updated` — the same silent reversion a re-run must not perform, with
 * a file this never wrote.
 */
const install = (dir: string, entry: string): InitChange => {
  const file = `${WORKFLOW_DIR}/${CALLER_PREFIX}${entry}`;
  const full = path.join(dir, ...file.split("/"));
  if (fs.existsSync(full)) {
    return {
      file,
      action: "kept",
      note: `a file of that name is already here and calls something else — rename it, or copy examples/callers/${entry} in by hand`,
    };
  }
  return { file, action: put(full, pinnedReference(entry, file)) };
};

/**
 * Pin what is installed, install what is not, and write the prompt for what is
 * left. Returns one entry per file considered, so a re-run that changed nothing
 * can be reported as such — and so every refusal is visible rather than being
 * the absence of a line.
 */
export const init = (options: InitOptions): readonly InitChange[] => {
  const { dir } = options;
  const installed = readInstalledCallers(dir, PACKAGE_NAME);

  // One entry per *file*, not per caller: two jobs of ours in one file is a
  // shape an adopter may well have, and it holds one pin rewrite between them.
  const files = [...new Set(installed.map((caller) => caller.file))];
  const changes: InitChange[] = files.map((file) => repin(dir, file));

  const present = new Set(installed.map((caller) => caller.workflow));
  const workflows = [...present];
  const callerFiles = [...files];

  for (const entry of referenceFiles()) {
    const name = entry.replace(/\.yml$/, "");
    if (present.has(name)) continue;

    // A first run scaffolds the lot. After that the subset is the adopter's
    // decision — a deleted caller stays deleted, and a workflow added in a
    // later release is named here rather than written into their tree behind
    // them, `pull_request_target` being what it is.
    if (installed.length > 0) {
      changes.push({
        file: `${WORKFLOW_DIR}/${CALLER_PREFIX}${entry}`,
        action: "kept",
        note: `no job here calls \`${name}\`; copy examples/callers/${entry} in and re-run to have it pinned`,
      });
      continue;
    }

    const change = install(dir, entry);
    changes.push(change);
    if (change.action === "kept") continue;

    workflows.push(name);
    callerFiles.push(change.file);
  }

  changes.push(putSetup(dir, workflows, callerFiles));
  return changes;
};

/**
 * The one file here that is not ours by construction. `SETUP.md` is a name an
 * adopter may already be using for something of their own, and overwriting a
 * document somebody wrote is not the same act as updating a caller this wrote —
 * so it carries a marker, and without it the file is left alone and reported.
 */
const putSetup = (
  dir: string,
  workflows: readonly string[],
  callers: readonly string[],
): InitChange => {
  const full = path.join(dir, SETUP_FILE);
  if (fs.existsSync(full) && !fs.readFileSync(full, "utf8").includes(setupMarker())) {
    return {
      file: SETUP_FILE,
      action: "kept",
      note: `not written by ${PACKAGE_NAME} — rename it and re-run to get the setup prompt`,
    };
  }
  return { file: SETUP_FILE, action: put(full, renderSetup(workflows, callers)) };
};
