import * as fs from "node:fs";
import * as path from "node:path";
import { PACKAGE_NAME, VERSION } from "../shared/manifest.js";
import { escapeRe, rewritePins, WORKFLOW_DIR } from "../shared/pins.js";
import { callersIn, readInstalledCallers, repoSlug, type InstalledCaller } from "./callers.js";

/**
 * The install path: scaffold into an adopter's repository what nothing upstream
 * covers, which is the GitHub Actions half of the loop.
 *
 * Since the reference callers became real files under test (#98),
 * `examples/callers/` is the source and this **copies** rather than generates.
 * That is the smaller job and the better one: a generator is a second
 * description of a caller, and the first release after it drifts is one where an
 * adopter installs something the suite has never seen.
 *
 * Two things in a caller are per-repo and are therefore substituted:
 *
 * - the **pin**, which should be this package's own version at the time `init`
 *   runs, through the same rewrite the release performs (`shared/pins.ts`);
 * - **`self-check`**, which is `<caller job id> / <called job id>` and is the
 *   one value nothing on the other side can read. It is composed from the job id
 *   being written rather than copied, so an adopter who renamed their job keeps
 *   the rename and gets a `self-check` that still matches it.
 *
 * And it **updates on a re-run** rather than refusing. The commonest reason to
 * run this twice is a new release; a scaffolder that says "remove it first" is
 * one an adopter works around by hand, which is how the pin went four releases
 * stale in the repository this loop was piloted on.
 */

/**
 * The reference callers, resolved the way a runner resolves its prompt —
 * relative to this module, so the same path works in a checkout and in the
 * tarball `scripts/copy-assets.ts` builds.
 */
const REFERENCE_DIR = path.join(import.meta.dirname, "..", "examples", "callers");

/** The prompt for the judgement work, and the marker that says we wrote it. */
const SETUP_TEMPLATE = path.join(import.meta.dirname, "SETUP.md");
const SETUP_FILE = "SETUP.md";

/**
 * What the template's first line says once substituted. Specific enough that an
 * adopter's own `SETUP.md` cannot match it by accident, and visible enough that
 * deleting the line is how you opt out of having it rewritten.
 */
const setupMarker = (): string => `generated by ${PACKAGE_NAME} init`;

/**
 * The reference filename an adopter gets when nothing is installed yet. The
 * prefix exists so a caller does not collide by filename with the reusable half
 * it calls; `readInstalledCallers` recognises a caller by what it calls, so a
 * rename survives a re-run.
 */
const CALLER_PREFIX = "agent-";

/**
 * The state labels every installation needs, whichever callers were taken.
 * The trigger labels are derived from the callers instead — see `labelsFor`.
 */
const STATE_LABELS: readonly { readonly name: string; readonly color: string; readonly description: string }[] = [
  { name: "agent:in-progress", color: "FBCA04", description: "An agent run is currently active" },
  { name: "agent:blocked", color: "B60205", description: "A run failed or was refused; needs human attention" },
];

const TRIGGER_LABELS: Readonly<Record<string, { readonly color: string; readonly description: string }>> = {
  "agent:implement": { color: "0E8A16", description: "Ready for the implement workflow to run" },
  "agent:review": { color: "1D76DB", description: "PR is ready for the automated review workflow" },
  "agent:fix": { color: "1D76DB", description: "Address review feedback on this PR" },
  "agent:update-branch": { color: "5319E7", description: "Refresh this PR branch from its base branch" },
};

/**
 * Which label triggers a given workflow. `implement-prd` shares `agent:implement`
 * with `implement` — the two partition every label event by issue shape — so it
 * contributes no label of its own.
 */
export const triggerLabel = (workflow: string): string =>
  `agent:${workflow === "implement-prd" ? "implement" : workflow}`;

/** The labels an installation of exactly these workflows needs, in a stable order. */
export const labelsFor = (workflows: readonly string[]): readonly string[] => {
  const triggers = Object.keys(TRIGGER_LABELS).filter((label) =>
    workflows.some((workflow) => triggerLabel(workflow) === label),
  );
  return [...triggers, ...STATE_LABELS.map((label) => label.name)];
};

export interface InitChange {
  /** Repo-relative, forward-slashed. */
  readonly file: string;
  readonly action: "created" | "updated" | "unchanged" | "kept";
  /** Why, on the one action that is a refusal rather than a write. */
  readonly note?: string;
}

export interface InitOptions {
  /** The adopting repository's root. */
  readonly dir: string;
}

const referenceFiles = (): readonly string[] =>
  fs
    .readdirSync(REFERENCE_DIR)
    .filter((entry) => entry.endsWith(".yml"))
    .sort();

/**
 * Rename the single job in a caller, in the text rather than by re-emitting the
 * YAML: every line of a caller except the two being substituted is a comment
 * explaining why the line under it is there, and a round-trip through a parser
 * throws all of it away.
 */
const withJobId = (text: string, from: string, to: string): string => {
  if (from === to) return text;
  const renamed = text.replace(new RegExp(`^(  )${escapeRe(from)}:$`, "m"), `$1${to}:`);
  if (renamed === text) {
    throw new Error(
      `Could not rename the job \`${from}\` to \`${to}\`: no \`  ${from}:\` line under \`jobs:\`. ` +
        `A caller's job id is the first half of \`self-check\`, so writing one without the other ` +
        `would install a review that waits for itself.`,
    );
  }
  return renamed;
};

/**
 * Recompose `self-check` around the job id actually being written, keeping the
 * called half — which is the reference's to know and nothing here can read, the
 * reusable workflows not being part of the tarball.
 */
const withSelfCheck = (text: string, jobId: string): string =>
  text.replace(
    /^(\s*self-check:[ \t]*)([\w.-]+)[ \t]*\/[ \t]*([\w.-]+)[ \t]*$/m,
    `$1${jobId} / $3`,
  );

/**
 * Read back what is about to be written and check the one coupling that has no
 * runtime symptom: `self-check` must name the job it sits in.
 *
 * Both substitutions are text edits against a file this does not own, so either
 * can quietly match nothing after a reword on the other side. A `self-check`
 * left naming the reference's job id is a review that waits for itself for 15 of
 * its 20 minutes and then reviews on degraded evidence — precisely the class of
 * defect that must not be written to disk on the strength of a regex having
 * been applied.
 */
const assertCoupled = (
  text: string,
  file: string,
  jobId: string,
  reference: InstalledCaller,
): void => {
  const written = callersIn(text, PACKAGE_NAME, file)[0];
  const named = written?.selfCheck?.split("/")[0]?.trim();

  if (written === undefined || written.jobId !== jobId) {
    throw new Error(`Refusing to write ${file}: it would not declare the job \`${jobId}\`.`);
  }
  if (reference.selfCheck !== undefined && named !== jobId) {
    throw new Error(
      `Refusing to write ${file}: \`self-check\` would be ${JSON.stringify(written.selfCheck)} on a ` +
        `job whose id is \`${jobId}\`. The check run is named \`<caller job id> / <called job id>\`, ` +
        `so the wait would not recognise its own and would wait for itself.`,
    );
  }
};

/** What a write did, without writing the same bytes twice. */
const put = (full: string, text: string): "created" | "updated" | "unchanged" => {
  if (!fs.existsSync(full)) {
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, text);
    return "created";
  }
  if (fs.readFileSync(full, "utf8") === text) return "unchanged";
  fs.writeFileSync(full, text);
  return "updated";
};

const renderSetup = (workflows: readonly string[], callers: readonly string[]): string => {
  const labels = labelsFor(workflows).map((name) => {
    const meta = TRIGGER_LABELS[name] ?? STATE_LABELS.find((label) => label.name === name);
    return `gh label create "${name}" --color ${meta?.color ?? "EDEDED"} --description "${meta?.description ?? ""}"`;
  });

  return fs
    .readFileSync(SETUP_TEMPLATE, "utf8")
    .replaceAll("{{PACKAGE}}", PACKAGE_NAME)
    .replaceAll("{{VERSION}}", VERSION)
    .replaceAll("{{SLUG}}", repoSlug(PACKAGE_NAME))
    .replaceAll("{{CALLERS}}", callers.join("\n"))
    .replaceAll("{{LABELS}}", labels.join("\n"));
};

/**
 * Copy the reference callers into `dir`, pinned to this package's version, and
 * write the prompt for what is left. Returns one entry per file considered, so
 * the caller can report a re-run that changed nothing as such.
 */
export const init = (options: InitOptions): readonly InitChange[] => {
  const { dir } = options;
  const installed = readInstalledCallers(dir, PACKAGE_NAME);
  const byWorkflow = new Map<string, InstalledCaller>(
    installed.map((caller) => [caller.workflow, caller]),
  );

  const changes: InitChange[] = [];
  const workflows: string[] = [];

  for (const entry of referenceFiles()) {
    const name = entry.replace(/\.yml$/, "");
    const text = fs.readFileSync(path.join(REFERENCE_DIR, entry), "utf8");

    const { text: pinned, found } = rewritePins(text, {
      packageName: PACKAGE_NAME,
      version: VERSION,
    });
    if (!found.includes("ref")) {
      throw new Error(
        `${entry} carries no \`uses:\` pin this version knows how to rewrite. Installing it would ` +
          `point an adopter at whichever release the reference happened to be written against.`,
      );
    }

    const reference = callersIn(pinned, PACKAGE_NAME, entry)[0];
    if (reference === undefined) {
      throw new Error(`${entry} declares no job calling ${PACKAGE_NAME}; it is not a caller.`);
    }

    // Their job id if they have one, ours otherwise — so a rename survives a
    // re-run and `self-check` is recomposed around it rather than reset.
    const existing = byWorkflow.get(name);
    const jobId = existing?.jobId ?? reference.jobId;
    const file = existing?.file ?? `${WORKFLOW_DIR}/${CALLER_PREFIX}${entry}`;

    const body = withSelfCheck(withJobId(pinned, reference.jobId, jobId), jobId);
    assertCoupled(body, file, jobId, reference);

    changes.push({ file, action: put(path.join(dir, ...file.split("/")), body) });
    workflows.push(name);
  }

  const callerFiles = changes.map((change) => change.file);
  changes.push(putSetup(dir, workflows, callerFiles));
  return changes;
};

/**
 * The one file here that is not ours by construction. `SETUP.md` is a name an
 * adopter may already be using for something of their own, and overwriting a
 * document somebody wrote is not the same act as updating a caller this wrote —
 * so it carries a marker, and without it the file is left alone and reported.
 */
const putSetup = (
  dir: string,
  workflows: readonly string[],
  callers: readonly string[],
): InitChange => {
  const full = path.join(dir, SETUP_FILE);
  if (fs.existsSync(full) && !fs.readFileSync(full, "utf8").includes(setupMarker())) {
    return {
      file: SETUP_FILE,
      action: "kept",
      note: `not written by ${PACKAGE_NAME} — rename it and re-run to get the setup prompt`,
    };
  }
  return { file: SETUP_FILE, action: put(full, renderSetup(workflows, callers)) };
};
