import * as fs from "node:fs";
import * as path from "node:path";
import { PACKAGE_NAME, VERSION } from "../shared/manifest.js";
import { rewritePins, WORKFLOW_DIR } from "../shared/pins.js";
import {
  callersIn,
  readInstalledCallers,
  type InstalledCaller,
  repoSlug,
  selfCheckFor,
  selfCheckMatches,
} from "./callers.js";
import {
  policyBody,
  policyCommand,
  POLICY_NAME,
  POLICY_SETTINGS,
  triggeredFiles,
  unallowedFiles,
  unreadable,
  type PolicySurface,
} from "./policies.js";
import type { LabelSurface } from "./labels.js";

/**
 * The install path: scaffold into an adopter's repository what nothing upstream
 * covers, which is the GitHub Actions half of the loop.
 *
 * Since the reference callers became real files under test,
 * `examples/callers/` is the source and this **copies** rather than generates.
 * That is the smaller job and the better one: a generator is a second
 * description of a caller, and the first release after it drifts is one where an
 * adopter installs something the suite has never seen.
 *
 * The one thing in a caller that is per-repo is the **pin**, which should be
 * this package's own version at the time `init` runs, and it is written through
 * the same rewrite the release performs (`shared/pins.ts`).
 *
 * And it **updates on a re-run** rather than refusing. The commonest reason to
 * run this twice is a new release; a scaffolder that says "remove it first" is
 * one an adopter works around by hand, which is how the pin went four releases
 * stale in the repository this loop was piloted on.
 *
 * So a re-run is **not** a second copy. A caller is what an adopter owns
 * (CONTEXT.md) — their trigger, their permissions, the `with:` inputs
 * `docs/ADOPTING.md` §4 ships commented out for them to enable, a job id they
 * renamed, a second job in the same file — and a re-run that rewrote the file
 * from the reference would revert every one of those and report it as
 * `updated`. A pnpm repository that had set `setup: pnpm i --frozen-lockfile`
 * would then die at `npm ci` with nothing saying why: the failure class this
 * whole command exists to remove, recreated by the command itself.
 *
 * Therefore:
 *
 * - a caller **already installed** has its pin moved *in its own text* and
 *   nothing else touched;
 * - a caller **not installed** is copied from the reference, pinned — but only
 *   when this is a first run. Once any caller is installed, the subset an
 *   adopter took is a decision, and a re-run reports what is absent rather than
 *   writing a `pull_request_target` workflow nobody asked for back into their
 *   tree.
 *
 * What drifts as a result — a `permissions:` line a later release added — is
 * exactly what `doctor` names, with the fix, on the same footing as everything
 * else it will not silently change for you.
 */

/**
 * The reference callers, resolved the way a runner resolves its prompt —
 * relative to this module, so the same path works in a checkout and in the
 * tarball `scripts/copy-assets.ts` builds.
 */
const REFERENCE_DIR = path.join(import.meta.dirname, "..", "examples", "callers");

/** The prompt for the judgement work, and the marker that says we wrote it. */
const SETUP_TEMPLATE = path.join(import.meta.dirname, "SETUP.md");
const SETUP_FILE = "SETUP.md";

/**
 * What the template's first line says once substituted. Specific enough that an
 * adopter's own `SETUP.md` cannot match it by accident, and visible enough that
 * deleting the line is how you opt out of having it rewritten.
 */
const setupMarker = (): string => `generated by ${PACKAGE_NAME} init`;

/**
 * The reference filename an adopter gets when nothing is installed yet. The
 * prefix exists so a caller does not collide by filename with the reusable half
 * it calls; `readInstalledCallers` recognises a caller by what it calls, so a
 * rename survives a re-run.
 */
const CALLER_PREFIX = "agent-";

/**
 * A label exactly as it has to be created: the name a workflow filters on, and
 * the colour and description `docs/ADOPTING.md` §3 gives it.
 *
 * Both tables below are a **second copy** of that §3 block — this one feeds
 * `SETUP.md`'s create commands and `doctor`'s missing-label errors, and the doc
 * is what a human reads. Held in step by `tests/agent-cli.test.ts`, which parses
 * §3 and compares, in the spirit of `PIN` in `tests/workflows.test.ts`: a rename
 * or a recolour in either place fails the build by name rather than leaving
 * `init` scaffolding one string and a workflow filtering on another.
 */
export interface LabelSpec {
  readonly name: string;
  readonly color: string;
  readonly description: string;
}

/**
 * The state labels every installation needs, whichever callers were taken.
 * The trigger labels are derived from the callers instead — see `labelSpecsFor`.
 */
export const STATE_LABELS: readonly LabelSpec[] = [
  { name: "agent:blocked", color: "CF222E", description: "A run failed or was refused. Needs you." },
];

/**
 * Coloured by **stage** (#236), so the colour on an issue or a pull request
 * says where in the lifecycle it is: build, review, fix, refresh. Each is on
 * while its run works and comes off when the run ends, which is what retired
 * `agent:in-progress`; the descriptions say so, since they are what GitHub
 * shows on hover.
 */
export const TRIGGER_LABELS: readonly LabelSpec[] = [
  {
    name: "agent:implement",
    color: "8250DF",
    description: "Build this issue, or the next slice of this PRD. On while the run works.",
  },
  { name: "agent:review", color: "0969DA", description: "Review this PR. On while the review runs." },
  { name: "agent:fix", color: "D4A72C", description: "Act on review findings. On while the fix runs." },
  {
    name: "agent:update-branch",
    color: "1B7C83",
    description: "Merge the base branch into this PR. On while it runs.",
  },
];

/**
 * Labels the loop wrote once and writes no longer. `init` deletes each where
 * no open issue or pull request still carries it, and `doctor` reports one
 * that is still there. Deleting a label strips it from everything carrying it,
 * so one still in use is left for a human, named.
 */
export const RETIRED_LABELS: readonly string[] = ["agent:in-progress", "agent:auto-fixed", "agent:queued"];

/** The one command that deletes a retired label, for `doctor`'s fix and `init`'s note. */
export const labelDeleteCommand = (name: string): string => `gh label delete "${name}" --yes`;

/**
 * Which label triggers a given workflow. `implement-prd` shares `agent:implement`
 * with `implement` — the two partition every label event by issue shape — so it
 * contributes no label of its own.
 */
export const triggerLabel = (workflow: string): string =>
  `agent:${workflow === "implement-prd" ? "implement" : workflow}`;

/** The labels an installation of exactly these workflows needs, in a stable order. */
export const labelSpecsFor = (workflows: readonly string[]): readonly LabelSpec[] => [
  ...TRIGGER_LABELS.filter((label) =>
    workflows.some((workflow) => triggerLabel(workflow) === label.name),
  ),
  ...STATE_LABELS,
];

/**
 * The labels `doctor` **does not demand**, keyed by the workflow that wants
 * them — every block `docs/ADOPTING.md` §3 prints after its first.
 *
 * Separate from the two tables above because the two halves that read them want
 * opposite things. `SETUP.md` should name every label the callers it just
 * installed will reach for, or an adopter gets a live feature whose only signal
 * is a `::warning::` inside a green run — the filing half marks nothing, files
 * its stubs unlabelled, and the next merge cannot see them. `doctor` should
 * *not* fail over them: none stops a loop a repository is actually running, and
 * a preflight that errors on a correctly-installed one is a preflight people
 * learn to skip. So these reach `renderSetup` and never `labelSpecsFor`.
 *
 * Conditional on the caller, which is why it is a map rather than a list: the
 * filing caller is the one file in the loop an adopter can decline (§4), and
 * labels prescribed to a repository that declined it are labels nothing in it
 * will ever read.
 */
export const ADVISORY_LABELS: Readonly<Record<string, readonly LabelSpec[]>> = {
  "follow-ups": [
    {
      name: "agent:follow-ups",
      color: "6E7781",
      description: "This PR's review recorded out-of-scope findings; they are filed on merge.",
    },
    { name: "pr-follow-up", color: "D4C5F9", description: "Filed from a merged PR's review by the follow-ups workflow" },
    { name: "needs-triage", color: "D93F0B", description: "Maintainer needs to evaluate this issue" },
  ],
};

/** Those of them an installation of exactly these workflows should be told about. */
export const advisoryLabelSpecsFor = (workflows: readonly string[]): readonly LabelSpec[] =>
  workflows.flatMap((workflow) => ADVISORY_LABELS[workflow] ?? []);

/**
 * A label exactly as it has to be created, as one line of shell.
 *
 * One definition, used by both halves: `SETUP.md` tells an adopter to run these
 * and `doctor` offers them as the fix for a label that does not exist. Only the
 * name decides anything at run time, so a second copy of the form would not
 * break a loop — it would just leave a repository that followed `doctor`'s
 * advice carrying five differently-coloured, undescribed labels from one that
 * ran `init`, and `docs/ADOPTING.md` §3 unable to be right about both.
 */
export const labelCommand = ({ name, color, description }: LabelSpec): string =>
  `gh label create "${name}" --color ${color} --description "${description}"`;

export interface InitChange {
  /**
   * Repo-relative, forward-slashed; or, for the one change that is not a file,
   * `POLICY_CHANGE`.
   */
  readonly file: string;
  /**
   * `kept` is the one that is a **refusal**: a file this will not write over,
   * or a caller an adopter does not have and this will not add for them. It
   * always carries the note saying which.
   */
  readonly action: "created" | "updated" | "unchanged" | "kept" | "deleted";
  /** Why — mandatory on `kept`, since a refusal nobody can read is a silence. */
  readonly note?: string;
}

export interface InitOptions {
  /** The adopting repository's root. */
  readonly dir: string;
  /**
   * Where the Actions policy is read and written: `livePolicySurface(dir)`
   * from the CLI, a stand-in from the tests. Required rather than defaulted to
   * the live one, so no call can reach a real GitHub without naming it; a
   * default made every test calling `init` spawn `gh` against whatever
   * repository the environment named.
   */
  readonly github: PolicySurface;
  /**
   * Where the labels are read and written: `liveLabelSurface(dir)` from the
   * CLI, a stand-in from the tests. Required for the same reason as `github`.
   */
  readonly labels: LabelSurface;
}

/** How the policy step names itself in the list of changes. */
export const POLICY_CHANGE = `Actions policy "${POLICY_NAME}"`;

const referenceFiles = (): readonly string[] =>
  fs
    .readdirSync(REFERENCE_DIR)
    .filter((entry) => entry.endsWith(".yml"))
    .sort();

/**
 * Read back what is about to be written and check the one coupling that has no
 * runtime symptom: `self-check` must name the job it sits in.
 *
 * The pin is a text edit against a file this does not own, and this reads the
 * result the way GitHub would rather than trusting that a regex was applied. A
 * `self-check` naming some other job is a review that waits for itself for 15 of
 * its 20 minutes and then reviews on degraded evidence — precisely the class of
 * defect that must not reach an adopter's disk, and the one thing here that no
 * test in *their* repository could catch.
 */
const assertCoupled = (text: string, file: string): void => {
  const written = callersIn(text, PACKAGE_NAME, file)[0];

  if (written === undefined) {
    throw new Error(`Refusing to write ${file}: it declares no job calling ${PACKAGE_NAME}.`);
  }
  // The same rule `doctor` rules on, from the same function rather than
  // written out twice: the whole name, byte for byte, since a `self-check`
  // naming the wrong called job — or the right two halves with the spaces
  // around the slash left out — is as invisible as one naming the wrong caller
  // job.
  if (!selfCheckMatches(written)) {
    throw new Error(
      `Refusing to write ${file}: \`self-check\` would be ${JSON.stringify(written.selfCheck)}, ` +
        `but the check run the \`${written.jobId}\` job produces is named ` +
        `\`${selfCheckFor(written)}\` — \`<calling job's name> / <called job's name>\` — so the ` +
        `wait would ` +
        `not recognise its own and would wait for itself.`,
    );
  }
};

/** What a write did, without writing the same bytes twice. */
const put = (full: string, text: string): "created" | "updated" | "unchanged" => {
  if (!fs.existsSync(full)) {
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, text);
    return "created";
  }
  if (fs.readFileSync(full, "utf8") === text) return "unchanged";
  fs.writeFileSync(full, text);
  return "updated";
};

const renderSetup = (workflows: readonly string[], callers: readonly string[]): string => {
  const labels = labelSpecsFor(workflows).map(labelCommand);
  const advisory = advisoryLabelSpecsFor(workflows).map(labelCommand);

  // Absent entirely rather than present and empty, placeholder line included:
  // a heading over nothing reads as a step somebody forgot to finish, and a
  // repository that declined the filing caller has no step here to finish.
  //
  // Uncounted, and that is deliberate rather than clumsy prose: the list is
  // per caller, so a repository that took some of them gets some of these, and
  // a number written here would be right for the installation this file was
  // authored against and wrong for the next one.
  const advisoryBlock =
    advisory.length === 0
      ? ""
      : [
          "",
          "**More labels, for the callers listed at the top of this file.** None of them is a",
          "transition and the check at the bottom demands none of them — but a review then marks",
          "nothing, a filed issue arrives unlabelled (invisible to the triage queue it was filed for,",
          "and to the duplicate check the next merge runs).",
          "",
          "```bash",
          ...advisory,
          "```",
          "",
        ].join("\n");

  return fs
    .readFileSync(SETUP_TEMPLATE, "utf8")
    .replace("\n{{ADVISORY_LABELS}}\n", advisoryBlock)
    .replaceAll("{{PACKAGE}}", PACKAGE_NAME)
    // The npm scope on its own — `@owner` — which is what an `.npmrc` registry
    // line is keyed on, and the one substitution that is a *part* of the name
    // rather than the name.
    .replaceAll("{{SCOPE}}", PACKAGE_NAME.split("/")[0] ?? PACKAGE_NAME)
    .replaceAll("{{VERSION}}", VERSION)
    .replaceAll("{{SLUG}}", repoSlug(PACKAGE_NAME))
    .replaceAll("{{CALLERS}}", callers.join("\n"))
    .replaceAll("{{LABELS}}", labels.join("\n"));
};

const pinnedReference = (entry: string, file: string): string => {
  const { text, found } = rewritePins(fs.readFileSync(path.join(REFERENCE_DIR, entry), "utf8"), {
    packageName: PACKAGE_NAME,
    version: VERSION,
  });
  if (!found.includes("ref")) {
    throw new Error(
      `${entry} carries no \`uses:\` pin this version knows how to rewrite. Installing it would ` +
        `point an adopter at whichever release the reference happened to be written against.`,
    );
  }
  assertCoupled(text, file);
  return text;
};

/**
 * Move an installed caller's pin to this version, **in the adopter's own file**.
 *
 * Every other line of it is theirs — see the header. `rewritePins` matches a
 * `@v<major.minor.patch>` ref and nothing else, so a caller deliberately pinned
 * to a SHA, or wrongly pinned to a branch, is reported rather than converted:
 * the first is a choice this has no business overriding and the second is a
 * finding `doctor` already raises by name.
 */
const repin = (dir: string, file: string): InitChange => {
  const full = path.join(dir, ...file.split("/"));
  const { text, found } = rewritePins(fs.readFileSync(full, "utf8"), {
    packageName: PACKAGE_NAME,
    version: VERSION,
  });
  if (!found.includes("ref")) {
    return {
      file,
      action: "kept",
      note: `its \`uses:\` ref is not a \`@v<version>\` tag, so it is left exactly as pinned`,
    };
  }
  return { file, action: put(full, text) };
};

/**
 * Install the reference caller for `entry`, unless something already occupies
 * the filename. A file there that is not one of ours is an adopter's own
 * workflow that happens to share the name, and `put` would overwrite it and
 * report `updated` — the same silent reversion a re-run must not perform, with
 * a file this never wrote.
 */
const install = (dir: string, entry: string): InitChange => {
  const file = `${WORKFLOW_DIR}/${CALLER_PREFIX}${entry}`;
  const full = path.join(dir, ...file.split("/"));
  if (fs.existsSync(full)) {
    return {
      file,
      action: "kept",
      note: `a file of that name is already here and calls something else — rename it, or copy examples/callers/${entry} in by hand`,
    };
  }
  return { file, action: put(full, pinnedReference(entry, file)) };
};

/**
 * Pin what is installed, install what is not, and write the prompt for what is
 * left. Returns one entry per file considered, so a re-run that changed nothing
 * can be reported as such — and so every refusal is visible rather than being
 * the absence of a line.
 */
export const init = (options: InitOptions): readonly InitChange[] => {
  const { dir } = options;
  const installed = readInstalledCallers(dir, PACKAGE_NAME);

  // One entry per *file*, not per caller: two jobs of ours in one file is a
  // shape an adopter may well have, and it holds one pin rewrite between them.
  const files = [...new Set(installed.map((caller) => caller.file))];
  const changes: InitChange[] = files.map((file) => repin(dir, file));

  const present = new Set(installed.map((caller) => caller.workflow));
  const workflows = [...present];
  const callerFiles = [...files];

  for (const entry of referenceFiles()) {
    const name = entry.replace(/\.yml$/, "");
    if (present.has(name)) continue;

    // A first run scaffolds the lot. After that the subset is the adopter's
    // decision — a deleted caller stays deleted, and a workflow added in a
    // later release is named here rather than written into their tree behind
    // them, `pull_request_target` being what it is.
    if (installed.length > 0) {
      changes.push({
        file: `${WORKFLOW_DIR}/${CALLER_PREFIX}${entry}`,
        action: "kept",
        note: `no job here calls \`${name}\`; copy examples/callers/${entry} in and re-run to have it pinned`,
      });
      continue;
    }

    const change = install(dir, entry);
    changes.push(change);
    if (change.action === "kept") continue;

    workflows.push(name);
    callerFiles.push(change.file);
  }

  changes.push(putSetup(dir, workflows, callerFiles));

  const policy = allowPullRequestTarget(
    readInstalledCallers(dir, PACKAGE_NAME),
    options.github,
  );
  if (policy !== undefined) changes.push(policy);
  changes.push(...convergeLabels(workflows, options.labels));
  return changes;
};

/** How a label names itself in the list of changes. */
export const labelChange = (name: string): string => `label "${name}"`;

/**
 * Every label the loop owns, as `docs/ADOPTING.md` §3 defines it (#236): the
 * `agent:*` labels the installed callers reach for, and `agent:follow-ups`
 * whichever callers were taken, since the review adds it whether or not the
 * filing caller is installed. The triage labels beside them are a vocabulary of
 * their own and an adopter's, so they are named in `SETUP.md` and never
 * written here.
 */
const ownedLabels = (workflows: readonly string[]): readonly LabelSpec[] => [
  ...labelSpecsFor(workflows),
  ...Object.values(ADVISORY_LABELS)
    .flat()
    .filter((label) => label.name.startsWith("agent:")),
];

/**
 * Create a missing label, edit one whose colour or description differs, and
 * leave one that matches, so a second run reports every label `unchanged`.
 * Then delete each retired label that is still here, unless an open issue or
 * pull request carries it: that one is left, and the note says where it is.
 *
 * Never fails the install, for the policy step's reason: the callers are on
 * disk by now, and a token that cannot write a label leaves a step a human can
 * take, named with the command.
 */
const convergeLabels = (workflows: readonly string[], github: LabelSurface): readonly InitChange[] => {
  const wanted = ownedLabels(workflows);
  const present = github.labels();
  if (present === undefined) {
    return [
      {
        file: "labels",
        action: "kept",
        note:
          `could not list this repository's labels, so none was created or recoloured; ` +
          `run ${wanted.map(labelCommand).join(" && ")}`,
      },
    ];
  }

  const byName = new Map(present.map((label) => [label.name, label]));
  const changes: InitChange[] = wanted.map((label): InitChange => {
    const file = labelChange(label.name);
    const current = byName.get(label.name);
    if (current === undefined) {
      const refused = github.create(label);
      return refused === undefined
        ? { file, action: "created" }
        : { file, action: "kept", note: `GitHub refused to create it (${refused}); run ${labelCommand(label)}` };
    }
    // GitHub answers the colour in lower case whatever it was given.
    if (current.color.toLowerCase() === label.color.toLowerCase() && current.description === label.description) {
      return { file, action: "unchanged" };
    }
    const refused = github.edit(label);
    return refused === undefined
      ? { file, action: "updated", note: `colour and description as docs/ADOPTING.md §3 gives them` }
      : {
          file,
          action: "kept",
          note: `GitHub refused to edit it (${refused}); run gh label edit "${label.name}" --color ${label.color} --description "${label.description}"`,
        };
  });

  for (const name of RETIRED_LABELS) {
    if (!byName.has(name)) continue;
    const file = labelChange(name);
    const carriers = github.carriers(name);
    if (carriers === undefined) {
      changes.push({
        file,
        action: "kept",
        note: `retired, but whether an open issue or PR still carries it could not be read; once none does, run ${labelDeleteCommand(name)}`,
      });
      continue;
    }
    if (carriers.length > 0) {
      changes.push({
        file,
        action: "kept",
        note: `retired, but still on ${carriers.map((n) => `#${n}`).join(", ")}; once none of them carries it, run ${labelDeleteCommand(name)}`,
      });
      continue;
    }
    const refused = github.remove(name);
    changes.push(
      refused === undefined
        ? { file, action: "deleted", note: `retired, and no open issue or PR carried it` }
        : { file, action: "kept", note: `retired, but GitHub refused to delete it (${refused}); run ${labelDeleteCommand(name)}` },
    );
  }
  return changes;
};

/**
 * Let the callers keep running on a public repository once GitHub blocks
 * `pull_request_target` there by default (#219): an Actions event policy
 * allowing it for **the callers' files and nothing else**, so every other
 * workflow in the repository stays under the block. `setup/policies.ts` holds
 * the shape and why it is that shape.
 *
 * Idempotent: a policy already allowing it for every caller is `unchanged`,
 * whoever wrote it. One this wrote that is short of a caller added since is
 * extended in place rather than doubled. And it never fails the install: the
 * callers are on disk by now, and a token that cannot write the policy is a
 * step left to a human, named with the exact call and the settings page.
 *
 * A private or internal repository is outside the rule and hears nothing.
 */
const allowPullRequestTarget = (
  callers: readonly InstalledCaller[],
  github: PolicySurface,
): InitChange | undefined => {
  const triggered = triggeredFiles(callers);
  if (triggered.length === 0) return undefined;

  const byHand = (why: string, files: readonly string[]): InitChange => ({
    file: POLICY_CHANGE,
    action: "kept",
    note:
      `${why} GitHub blocks \`pull_request_target\` on a public repository from 2026-11-02 unless a ` +
      `policy allows it, and ${files.join(", ")} run on it. As a repository admin, run ` +
      `\`${policyCommand(policyBody(callers, files))}\`, or add it under ${POLICY_SETTINGS}`,
  });

  const visibility = github.visibility();
  if (visibility === "private") return undefined;
  if (visibility === undefined) {
    return byHand(`Could not read this repository's visibility; a private one needs nothing here.`, triggered);
  }

  const policies = github.policies();
  if (policies === undefined) return byHand(`Could not read this repository's Actions policies.`, triggered);

  const unallowed = unallowedFiles(callers, policies);
  if (unallowed.length === 0) {
    return { file: POLICY_CHANGE, action: "unchanged", note: `allows \`pull_request_target\` for ${triggered.join(", ")}` };
  }

  // One that could not be read may be the one allowing them, or this step's
  // own: creating a second beside it is a write on a fact nobody read.
  if (unreadable(policies)) {
    return byHand(`Could not read every Actions policy that applies to this repository.`, unallowed);
  }

  const ours = policies.find((policy) => policy?.name === POLICY_NAME && policy.id !== undefined);
  if (ours?.id !== undefined) {
    // Switched off, or to evaluate, by somebody: that is a decision, and
    // turning it back on behind them is the silent reversion a re-run must
    // never perform.
    if (ours.enforcement !== "active") {
      return {
        file: POLICY_CHANGE,
        action: "kept",
        note: `its enforcement is \`${ours.enforcement}\`, which allows nothing; set it to active under ${POLICY_SETTINGS} if that was not deliberate`,
      };
    }
    const files = [...new Set([...(ours.include ?? []), ...unallowed])].sort();
    const refused = github.update(ours.id, policyBody(callers, files, ours.allowedEvents ?? []));
    return refused === undefined
      ? { file: POLICY_CHANGE, action: "updated", note: `now allows \`pull_request_target\` for ${unallowed.join(", ")} too` }
      : byHand(`GitHub refused the update (${refused}).`, unallowed);
  }

  const refused = github.create(policyBody(callers, unallowed));
  return refused === undefined
    ? { file: POLICY_CHANGE, action: "created", note: `allows \`pull_request_target\` for ${unallowed.join(", ")} and no other workflow` }
    : byHand(`GitHub refused to create it (${refused}).`, unallowed);
};

/**
 * Whether `dir` is this package's own checkout (#238), by the name its
 * manifest declares. Its callers are real and pinned like anyone's, but the
 * setup prompt is an adopter's to-do list, and here it is a stray file at the
 * root of the repository that wrote it.
 */
const isOwnRepository = (dir: string): boolean => {
  try {
    const manifest: unknown = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    return typeof manifest === "object" && manifest !== null && (manifest as { name?: unknown }).name === PACKAGE_NAME;
  } catch {
    return false;
  }
};

/**
 * The one file here that is not ours by construction. `SETUP.md` is a name an
 * adopter may already be using for something of their own, and overwriting a
 * document somebody wrote is not the same act as updating a caller this wrote —
 * so it carries a marker, and without it the file is left alone and reported.
 */
const putSetup = (
  dir: string,
  workflows: readonly string[],
  callers: readonly string[],
): InitChange => {
  if (isOwnRepository(dir)) {
    return {
      file: SETUP_FILE,
      action: "kept",
      note: `this is ${PACKAGE_NAME}'s own repository, and the setup prompt is for an adopter's`,
    };
  }
  const full = path.join(dir, SETUP_FILE);
  if (fs.existsSync(full) && !fs.readFileSync(full, "utf8").includes(setupMarker())) {
    return {
      file: SETUP_FILE,
      action: "kept",
      note: `not written by ${PACKAGE_NAME} — rename it and re-run to get the setup prompt`,
    };
  }
  return { file: SETUP_FILE, action: put(full, renderSetup(workflows, callers)) };
};
